### ISSUE TITLE
SKK辞書のコメント行に改行文字を付加して欲しい

### ISSUE THREAD

**Issue by nathancorvussolis** [kb10uy/ongeki-data#2]
「;; okuri-ari entries.」および「;; okuri-nasi entries.」を出力する際、それぞれ改行文字が欲しいです。

あと余談ですがライセンスを決めてくださるとありがたいです。

**Comment by kb10uy** [comment]
改行を追加しました。ご報告ありがとうございます。
ライセンスについてですが、 [skk-dict-imascg](https://github.com/project-brightblue/skk-dict-imascg) が CC0 となっていたので CC-BY 4.0 としました。
